### ISSUE TITLE
🐛 TS build does not pass

### ISSUE THREAD

**Issue by NoahTheNerd** [NoahTheNerd/lavacake#15]
Gonna be for real, I have no idea.
- I have no idea how to disable this.
- I have no idea how to fix this.
- I have no idea what I am going to do about this.

**Comment by robere2** [comment]
I fixed majority of errors here: https://github.com/NoahTheNerd/lavacake/compare/master...robere2:lavacake:fix-tsc

Outline of changes:
- I added `config.json` and `package.json` to the TypeScript project so you can reference them in TypeScript code. This error is mostly relevant if you're using `tsc` to compile your TypeScript into JavaScript files. Since we're just using `tsc` to make sure there are no TypeScript errors (i.e., the `noEmit` option in the `tsconfig.json` file), this error does not mean anything, but we can fix it anyway.
- Added `async` to the Promise callback in `getUUID`. The `await` keyword can only be used in async methods.
- Added a type check to make sure `lowerCaseName` isn't undefined. Since `params.get('name')` can return either a string or undefined, we need to check that it's not undefined to be type safe. Otherwise, `Cache[undefined]` is an error.
- I did not fix the error about [`formatUUID`](https://github.com/NoahTheNerd/lavacake/blob/master/src/utils/getUUID.ts#L32) because this method is commented out and I don't know what your goal is there.
